<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductFlowServer.DataAccess\ProductFlowServer.DataAccess.csproj" />
    <ProjectReference Include="..\ProductFlowServer.DTO\ProductFlowServer.DTO.csproj" />
    <ProjectReference Include="..\ProductFlowServer.Entities\ProductFlowServer.Entities.csproj" />
  </ItemGroup>

</Project>
